# GitHub labeler configuration
# Automatically apply labels based on file changes

# Frontend/UI changes
frontend:
  - 'src/**/*.tsx'
  - 'src/**/*.ts'
  - 'public/**/*'

# React components
components:
  - 'src/components/**/*'

# Pages/Routing
pages:
  - 'src/pages/**/*'

# Settings pages
settings:
  - 'src/pages/settings/**/*'

# Services/Logic
services:
  - 'src/services/**/*'

# Configuration
config:
  - '.github/**/*'
  - 'vite.config.ts'
  - 'tsconfig.json'
  - 'eslintrc.*'
  - '.prettierrc*'
  - 'package.json'
  - 'package-lock.json'

# Dependencies
dependencies:
  - 'package.json'
  - 'package-lock.json'

# Documentation
documentation:
  - '*.md'
  - 'docs/**/*'

# Legal
legal:
  - 'src/pages/legal/**/*'

# Build/Distribution
build:
  - 'dist/**/*'
  - 'build/**/*'
