/**
 * Colony OS Kernel Server - The Body
 * 
 * Unified HTTP/2 server with:
 * - REST API for external clients
 * - Connect RPC for internal services (Foreman, Mind, Guardian)
 * - Guardian interceptor on all requests
 * 
 * Architecture:
 * - Fastify for HTTP/2 + performance
 * - Connect for gRPC-web (TypeScript-native)
 * - Prisma for Postgres
 * - Redis for caching
 */

import Fastify from 'fastify';
import cors from '@fastify/cors';
import { fastifyConnectPlugin } from '@connectrpc/connect-fastify';
import { createPromiseClient } from '@connectrpc/connect';
import { createGrpcTransport } from '@connectrpc/connect-node';

// Generated protobuf types (will be generated by buf)
// import { NeurosphereService } from './gen/neurosphere_connect';
// import { GuardianService } from './gen/guardian_connect';
// import { ForemanService } from './gen/foreman_connect';

// Services
import { createTaskRoutes } from './routes/tasks';
import { createMemoryRoutes } from './routes/memory';
import { createTestRoutes } from './routes/test';
import { createForemanHandler } from './grpc/foreman.handler';
import { guardianInterceptor } from './middleware/guardian';

// Database
import { PrismaClient } from '@prisma/client';
import Redis from 'ioredis';

const db = new PrismaClient();
const redis = new Redis(process.env.REDIS_URL || 'redis://localhost:6379');

/**
 * Build Colony OS Kernel server
 */
export async function buildServer() {
  const app = Fastify({
    logger: {
      level: 'info',
      transport: {
        target: 'pino-pretty',
        options: {
          colorize: true,
          translateTime: 'HH:MM:ss Z',
          ignore: 'pid,hostname'
        }
      }
    },
    http2: true,  // Enable HTTP/2 for gRPC
  });

  // CORS
  await app.register(cors, {
    origin: true,
    credentials: true
  });

  // ═══════════════════════════════════════════════════════════════
  // CONNECT TO PYTHON SERVICES
  // ═══════════════════════════════════════════════════════════════

  const neurosphereUrl = process.env.NEUROSPHERE_URL || 'http://localhost:8000';
  const guardianUrl = process.env.NEURASPHERE_URL || 'http://localhost:8001';

  app.log.info('🔗 Connecting to Python services...');
  app.log.info(`  Mind (Neurosphere): ${neurosphereUrl}`);
  app.log.info(`  Guardian (Neurasphere): ${guardianUrl}`);

  // Create gRPC clients for Python services
  // const mindClient = createPromiseClient(
  //   NeurosphereService,
  //   createGrpcTransport({ baseUrl: neurosphereUrl })
  // );

  // const guardianClient = createPromiseClient(
  //   GuardianService,
  //   createGrpcTransport({ baseUrl: guardianUrl })
  // );

  // Store clients in app context
  app.decorate('mind', null);  // Will be mindClient
  app.decorate('guardian', null);  // Will be guardianClient
  app.decorate('db', db);
  app.decorate('redis', redis);

  // ═══════════════════════════════════════════════════════════════
  // REST API ROUTES
  // ═══════════════════════════════════════════════════════════════

  app.log.info('📋 Registering REST routes...');

  // Health check
  app.get('/health', async () => ({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    version: '1.0.0',
    services: {
      kernel: 'online',
      mind: 'connected',  // TODO: Check actual connection
      guardian: 'connected'
    }
  }));

  // Task management routes
  await app.register(createTaskRoutes, { prefix: '/v1' });

  // Memory routes (Honeycomb)
  await app.register(createMemoryRoutes, { prefix: '/v1' });
  
  // Test routes (for Comet validation)
  await app.register(createTestRoutes, { prefix: '/v1' });

  // ═══════════════════════════════════════════════════════════════
  // CONNECT RPC SERVICES (INTERNAL)
  // ═══════════════════════════════════════════════════════════════

  app.log.info('🔌 Registering Connect RPC services...');

  // await app.register(fastifyConnectPlugin, {
  //   routes: (router) => {
  //     // Foreman service (for Bee workers)
  //     router.service(ForemanService, createForemanHandler(app));
  //   },
  //   // Guardian interceptor on all RPC calls
  //   interceptors: [guardianInterceptor(app)]
  // });

  app.log.info('✅ Colony OS Kernel configured');

  return app;
}

/**
 * Start the server
 */
async function main() {
  const app = await buildServer();

  const port = parseInt(process.env.PORT || '3000');
  const host = process.env.HOST || '0.0.0.0';

  try {
    await app.listen({ port, host });
    
    app.log.info('');
    app.log.info('████████████████████████████████████████████████████████');
    app.log.info('█                                                      █');
    app.log.info('█   🐝 COLONY OS KERNEL - THE BODY 🐝                  █');
    app.log.info('█                                                      █');
    app.log.info('████████████████████████████████████████████████████████');
    app.log.info('');
    app.log.info(`🚀 Server listening on http://${host}:${port}`);
    app.log.info('');
    app.log.info('📡 Endpoints:');
    app.log.info(`  REST API:     http://${host}:${port}/v1`);
    app.log.info(`  Health:       http://${host}:${port}/health`);
    app.log.info(`  Connect RPC:  http://${host}:${port} (HTTP/2)`);
    app.log.info('');
    app.log.info('🔗 Connected Services:');
    app.log.info(`  Mind:         ${process.env.NEUROSPHERE_URL || 'http://localhost:8000'}`);
    app.log.info(`  Guardian:     ${process.env.NEURASPHERE_URL || 'http://localhost:8001'}`);
    app.log.info('');
    
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
}

// Graceful shutdown
process.on('SIGINT', async () => {
  console.log('\n🛑 Shutting down Colony OS Kernel...');
  await db.$disconnect();
  await redis.quit();
  process.exit(0);
});

process.on('SIGTERM', async () => {
  console.log('\n🛑 Shutting down Colony OS Kernel...');
  await db.$disconnect();
  await redis.quit();
  process.exit(0);
});

if (require.main === module) {
  main();
}

