-- ============================================
-- CRITICAL SECURITY FIX: RLS-001
-- SecurityBee Finding: Missing RLS policy on sensitive financial data
-- Module: finance_bee.py
-- ============================================
-- 
-- This migration fixes the CRITICAL vulnerability where users could
-- potentially access financial data belonging to other users.
--
-- Generated by: SecurityBee (BEE SWARM Governance Layer)
-- Issue ID: RLS-001
-- Severity: CRITICAL
-- ============================================

-- Step 1: Ensure RLS is enabled on user_profiles
-- (This should already be enabled, but we ensure it)
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Step 2: Drop existing policies if they exist (to avoid conflicts)
DROP POLICY IF EXISTS "Users can only read their own profile data" ON user_profiles;
DROP POLICY IF EXISTS "Users can update their own profile data" ON user_profiles;
DROP POLICY IF EXISTS "Users can read their own profile" ON user_profiles;
DROP POLICY IF EXISTS "Users can update their own profile" ON user_profiles;

-- Step 3: Create SELECT policy (READ access)
-- Users can only view their own profile data, including financial fields
CREATE POLICY "Users can only read their own profile data"
ON user_profiles FOR SELECT
TO authenticated
USING (auth.uid() = id);

-- Step 4: Create UPDATE policy (MODIFY access)
-- Users can update their own profile, but NOT sensitive financial fields
-- Financial fields (is_premium, subscription_tier, stripe_customer_id) 
-- should only be updated by service role via webhooks
-- Note: We use a function to prevent financial field modifications
CREATE OR REPLACE FUNCTION prevent_financial_field_modification()
RETURNS TRIGGER AS $$
BEGIN
  -- Prevent users from modifying their own financial status
  IF OLD.is_premium IS DISTINCT FROM NEW.is_premium THEN
    RAISE EXCEPTION 'Cannot modify is_premium field. This can only be updated by service role.';
  END IF;
  IF OLD.subscription_tier IS DISTINCT FROM NEW.subscription_tier THEN
    RAISE EXCEPTION 'Cannot modify subscription_tier field. This can only be updated by service role.';
  END IF;
  IF OLD.stripe_customer_id IS DISTINCT FROM NEW.stripe_customer_id THEN
    RAISE EXCEPTION 'Cannot modify stripe_customer_id field. This can only be updated by service role.';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to enforce financial field protection
DROP TRIGGER IF EXISTS prevent_financial_modification ON user_profiles;
CREATE TRIGGER prevent_financial_modification
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW
  WHEN (auth.role() = 'authenticated')
  EXECUTE FUNCTION prevent_financial_field_modification();

-- UPDATE policy allows users to update their own profile
CREATE POLICY "Users can update their own profile data"
ON user_profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Step 5: Create INSERT policy (for profile creation)
-- Users can create their own profile during signup
CREATE POLICY "Users can insert their own profile"
ON user_profiles FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = id);

-- Step 6: Ensure service role can manage all profiles (for webhooks)
-- This allows Stripe webhooks and backend services to update financial data
CREATE POLICY "Service role can manage all profiles"
ON user_profiles FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Step 7: Verify the policies are active
DO $$
DECLARE
  policy_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO policy_count
  FROM pg_policies
  WHERE schemaname = 'public'
    AND tablename = 'user_profiles';
  
  IF policy_count >= 3 THEN
    RAISE NOTICE '✅ RLS-001 FIXED: % policies created on user_profiles', policy_count;
  ELSE
    RAISE WARNING '⚠️  Only % policies found. Expected at least 3.', policy_count;
  END IF;
END $$;

-- ============================================
-- VERIFICATION QUERIES
-- Run these after migration to verify security
-- ============================================

-- Check RLS is enabled
SELECT 
  tablename,
  rowsecurity as rls_enabled
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename = 'user_profiles';

-- List all policies on user_profiles
SELECT 
  policyname,
  cmd as operation,
  qual as using_expression,
  with_check as with_check_expression
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename = 'user_profiles'
ORDER BY policyname;

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
-- Status: CRITICAL vulnerability RLS-001 has been fixed
-- SecurityBee finding addressed: ✅
-- ============================================

